# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: mitsuhiko.rye
PackageVersion: 0.13.0
InstallerType: exe
Installers:
- InstallerUrl: https://github.com/mitsuhiko/rye/releases/download/0.13.0/rye-x86-windows.exe
  Architecture: x86
  InstallerSha256: F89ADE3E9362741B02C245436E49908518C1F92677E33F366B47CDB000942A4E
- InstallerUrl: https://github.com/mitsuhiko/rye/releases/download/0.13.0/rye-x86_64-windows.exe
  Architecture: x64
  InstallerSha256: 749A8CAA46E834527AF4527825E0D829DFE758486963E038F27B3C00C5A75641
ManifestType: installer
ManifestVersion: 1.5.0
