# Created using wingetcreate 0.4.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.0.0.schema.json

PackageIdentifier: OpenStreetMap.Josm
PackageVersion: 18303
PackageLocale: bg-BG
Publisher: OpenStreetMap JOSM team
PackageUrl: https://josm.openstreetmap.de/wiki/Bg:WikiStart
ShortDescription: JOSM е редактор за OpenStreetMap (OSM) написан на Java 8
ManifestType: locale
ManifestVersion: 1.0.0

