# Created using wingetcreate 0.4.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.0.0.schema.json

PackageIdentifier: OpenStreetMap.Josm
PackageVersion: 18303
PackageLocale: cs-CZ
Publisher: OpenStreetMap JOSM team
PackageUrl: https://josm.openstreetmap.de/wiki/Cs:WikiStart
ShortDescription: JOSM je editor pro vytváření a úpravy OpenStreetMap (OSM) napsaný v Javě 8
ManifestType: locale
ManifestVersion: 1.0.0

