# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: ThornsoftDevelopmentInc.ClipMate
PackageVersion: 7.5.26
Installers:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: http://thornsoft.com/dist/ClipMate_7526_136.exe
  InstallerSha256: 9CB5EFC83B6899B7B22564BA6BFAA06C5C8DAE60EA4F92813C3C34AAFBCDBF8F
ManifestType: installer
ManifestVersion: 1.0.0

