# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Mirantis.Lens
PackageVersion: v5.3.4-latest.20220120.1
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://api.k8slens.dev/binaries/Lens%20Setup%205.3.4-latest.20220120.1.exe
  InstallerSha256: 7887E5825B4118C0D5D7EC3045A327BB1AFA5C9D98FD7CB67EC9EF7BA7EA2423
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://api.k8slens.dev/binaries/Lens%20Setup%205.3.4-latest.20220120.1.exe
  InstallerSha256: 7887E5825B4118C0D5D7EC3045A327BB1AFA5C9D98FD7CB67EC9EF7BA7EA2423
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.1.0

