# Created using wingetcreate

PackageIdentifier: Jigsaw.OutlineClient
PackageVersion: 1.6.0
PackageLocale: en-US
Publisher: Jigsaw
PackageName: Outline Client
License: Apache-2.0 License
ShortDescription: Outline clients, developed by Jigsaw. The Outline clients use the popular Shadowsocks protocol, and lean on the Cordova and Electron frameworks to support Windows, Android / ChromeOS, Linux, iOS and macOS.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
