# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: VeroLabsInc.VERO
PackageVersion: 0.4.15-beta
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://d28pqbmu81jtzp.cloudfront.net/vero-beta-0.4.15.exe
  InstallerSha256: E958523D39FBCB60A994BFC6C9DF36B2432B26E264A25248453CEA208C08E279
ManifestType: installer
ManifestVersion: 1.0.0

