# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: VeroLabsInc.VERO
PackageVersion: 0.4.15-beta
PackageLocale: en-US
Publisher: Vero Labs Inc
PublisherUrl: https://vero.co/
PublisherSupportUrl: https://verohelp.zendesk.com/hc/en-us/
PrivacyUrl: https://vero.co/privacy-policy
Author: Vero Labs Inc
PackageName: VERO
PackageUrl: https://brand.vero.co/vero-desktop-beta
License: Copyright © 2021 Vero Labs Inc
ShortDescription: Vero is a social media app that allows you to share things with those that follow or have connected with you.
Moniker: vero
Tags:
- beta
- social
ManifestType: defaultLocale
ManifestVersion: 1.0.0

